version: '3.8'

services:
  arvan-monitor:
    build: .
    container_name: arvan-wallet-monitor
    env_file: .env
    command: node arvan/arvan-wallet-check.js
    volumes:
      - ./data:/app/data
      - ./arvan:/app/arvan
      - ./data/sent-messages.json:/app/sent-messages.json
    restart: unless-stopped

  hamravesh-monitor:
    build: .
    container_name: hamravesh-wallet-monitor
    env_file: .env
    command: node hamravesh/hamravesh-monitor.js
    volumes:
      - ./hamravesh:/app/hamravesh
      - ./data/sent-messages.json:/app/sent-messages.json
    restart: unless-stopped